# Configuration settings
logging_level: 'INFO'

# Files
cdd_historical_file: 'data_experiencedT/historical/IEA-CMCC-WeatherForEnergy-CDD18dailybypop-from-2000-to-2020.csv'
gdp_historical_file: 'data_experiencedT/historical/API_NY.GDP.PCAP.PP.KD_DS2_en_csv_v2_5873868.csv'
cdd_projections_file: 'data_experiencedT/projections/ISO_CDD_GDP18_agg_data.csv'
gdp_projections_file: 'data_experiencedT/projections/gdp_edu_projections.csv'

ac_historical_file_iea: 'data_experiencedT/exposure_function_derivation/percentage-of-households-equiped-with-ac-in-selected-countries-2018.csv'
ac_historical_file_gdl: 'data_experiencedT/exposure_function_derivation/aircon_gdl.csv'
ac_historical_file_oecd: 'data_experiencedT/exposure_function_derivation/ac_oecd_epic.csv'

world_bank_income_groups_file: 'data_experiencedT/CLASS.xlsx'

output_path: 'data_experiencedT/cooling_deficit_index_calculations.csv'

# Availability function, either 'exponential' or 'combined_exponential'
availability_function: 'combined_exponential'

# Years
analysis_years:
  past_year: 1990
  ref_year: 2019
  future_year: 2100

# Scenarios
future_scenarios:
  - 'ssp1_rcp26'
  - 'ssp2_rcp45'
  - 'ssp5_rcp60'

# Income groups
income_groups_colors:
  low: 'fuchsia'
  lower middle: 'orange'
  upper middle: 'cyan'
  high: 'blue'

# Plotting settings
plotting:
  # Ranges
  cooling_deficit_index_max: 5000.
  cdd_min: 0.
  cdd_max: 4000.
  cdd_diff_max: 2000.
  gdp_max: 100000.
  gdp_min: 1000.
  contour_levels: 21
  gdp_growth_min: 0.
  gdp_growth_max: 5.
  # Labels
  exposure_times_cdd_label: 'Cooling Deficit Index (°C days)'
  cdd_label: 'Cooling Degree Days (°C days)'
  gdp_label: 'GDP per capita (2017 int. $)'
  # Color maps
  cdd_cmap: 'autumn_r'
  gdp_cmap: 'summer'
  exposure_times_cdd_cmap: 'inferno_r'
  ac_adoption_cmap: 'viridis'