# Configuration settings

logging_level: 'ERROR'

# Files

# Source: https://www.sciencedirect.com/science/article/pii/S0378778822004868
cdd_historical_file: 'data_experiencedT/DD_ProcessedComplete.csv'
# Source: https://data.worldbank.org/indicator/NY.GDP.PCAP.CD
# gdp_historical_file: 'data_experiencedT/API_NY.GDP.PCAP.CD_DS2_en_csv_v2_5871588.csv'
# Source: https://data.worldbank.org/indicator/NY.GDP.PCAP.PP.KD
# Purchasing power parity
gdp_historical_file: 'data_experiencedT/API_NY.GDP.PCAP.PP.KD_DS2_en_csv_v2_5873868.csv'
cdd_projections_file: 'data_experiencedT/projections/ISO_CDD_GDP18_agg_data.csv'
gdp_projections_file: 'data_experiencedT/projections/gdp_edu_projections.csv'

# Years
future_years: 
  # - 2040
  # - 2060
  # - 2080
  - 2100

ref_year: 2018
past_year: 1980

# Scenarios
base_future_scenario: 'ssp2_rcp45'

future_scenarios:
  - 'ssp1_rcp26'
  - 'ssp2_rcp45'
  - 'ssp5_rcp60' # don't have data higher than RCP 6.0

scenario_colors:
  - 'green'
  - 'blue'
  - 'red'

countries_highest_pop:
  - 'CHN'
  - 'IND'
  - 'USA'
  - 'IDN'
  - 'PAK'
  - 'BRA'
  - 'NGA'

continent_colors:
  Africa: 'red'
  Asia: 'green'
  Europe: 'blue'
  America: 'orange'
  Oceania: 'purple'