# Configuration settings

logging_level: 'ERROR'

# Files

cdd_historical_file: 'data_experiencedT/historical/DD_ProcessedComplete.csv'
gdp_historical_file: 'data_experiencedT/historical/API_NY.GDP.PCAP.PP.KD_DS2_en_csv_v2_5873868.csv'
cdd_projections_file: 'data_experiencedT/projections/ISO_CDD_GDP18_agg_data.csv'
gdp_projections_file: 'data_experiencedT/projections/gdp_edu_projections.csv'

ac_historical_file_iea: 'data_experiencedT/exposure_function_derivation/percentage-of-households-equiped-with-ac-in-selected-countries-2018.csv'
ac_historical_file_gdl: 'data_experiencedT/exposure_function_derivation/aircon_gdl.xlsx'
ac_historical_file_oecd: 'data_experiencedT/exposure_function_derivation/ac_oecd_epic.xlsx'

# Years
future_years: 
  # - 2040
  # - 2060
  # - 2080
  - 2100

ref_year: 2018
past_year: 1980

# Scenarios
base_future_scenario: 'ssp2_rcp45'

future_scenarios:
  - 'ssp1_rcp26'
  - 'ssp2_rcp45'
  - 'ssp5_rcp60' # don't have data higher than RCP 6.0

scenario_colors:
  - 'green'
  - 'blue'
  - 'red'

income_groups_colors:
  low: 'red'
  lower-middle: 'orange'
  middle: 'green'
  upper-middle: 'lightblue'
  high: 'darkblue'
  global average: 'black'

plotting:
  experiencedT_max: 4000.
  experiencedT_cmap: 'inferno_r'
  exposure_times_cdd_label: 'Experienced CDD (°C days)'
  contour_levels:
    absolute: 21
    low: 21
    lower-middle: 21
    middle: 41
    upper-middle: 51
    high: 101
    global average: 41
  gdp_growth_max: 6.
  gdp_growth_cmap: 'viridis'