# Configuration settings

logging_level: 'INFO'

# Files

cdd_historical_file: 'data_experiencedT/historical/IEA-CMCC-WeatherForEnergy-CDD18dailybypop-from-2000-to-2020.csv'
gdp_historical_file: 'data_experiencedT/historical/API_NY.GDP.PCAP.PP.KD_DS2_en_csv_v2_5873868.csv'
cdd_projections_file: 'data_experiencedT/projections/ISO_CDD_GDP18_agg_data.csv'
gdp_projections_file: 'data_experiencedT/projections/gdp_edu_projections.csv'

ac_historical_file_iea: 'data_experiencedT/exposure_function_derivation/percentage-of-households-equiped-with-ac-in-selected-countries-2018.csv'
ac_historical_file_gdl: 'data_experiencedT/exposure_function_derivation/aircon_gdl.csv'
ac_historical_file_oecd: 'data_experiencedT/exposure_function_derivation/ac_oecd_epic.csv'

output_path: 'data_experiencedT/heat_exposure_calculations.csv'

# Availability function, either 'power_law' or 'exponential' or 'combined_exponential'
availability_function: 'combined_exponential'

# Years
analysis_years:
  past_year: 1990
  ref_year: 2019
  future_year: 2100

# Scenarios
future_scenarios:
  - 'ssp1_rcp26'
  - 'ssp2_rcp45'
  - 'ssp5_rcp60' # don't have data higher than RCP 6.0

scenario_colors:
  - 'green'
  - 'blue'
  - 'red'

income_groups:
  - low
  - lower-middle
  - middle
  - upper-middle
  - high

income_groups_colors:
  low: 'red'
  lower-middle: 'orange'
  middle: 'green'
  upper-middle: 'lightblue'
  high: 'darkblue'
  global average: 'white'

plotting:
  experiencedT_max: 5000.
  cdd_min: 0.
  cdd_max: 5000.
  gdp_max: 100000.
  gdp_min: 1000.
  exposure_times_cdd_label: 'Heat exposure (°C days)'
  cdd_label: 'CDD pop-weighted (°C days)'
  gdp_label: 'GDP per capita PPP (2017 int. $)'
  contour_levels:
    absolute: 21
    low: 21
    lower-middle: 21
    middle: 41
    upper-middle: 51
    high: 101
    global average: 41
  gdp_growth_min: 0.
  gdp_growth_max: 5.
  exposure_times_cdd_cmap: 'inferno_r'
  cdd_cmap: 'inferno_r'
  gdp_growth_cmap: 'viridis'
  gdp_cmap: 'summer'
